# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cefda04e5e65a61c35d2212637cc2f695b194bbe2b7799ec3a51e610e8a9e8a36c4ef128a5a684f516fb06a1159e6d93961322fd1ae4dcfbf42b6c097d0b4236
  secret_url_cloudamqp_bunny: 'localhost'
  secret_url_cloudamqp_sneakers: 'amqp://guest:guest@localhost:5672'

test:
  secret_key_base: 0a3f8efa435f7e8274df14602508f5013180ed563390a10d30fa5e4e8676386353b6ed0a95077c4937e6323fdc4d06ea637af2793596acd72a4eaec0646e5304
  secret_url_cloudamqp_bunny: 'localhost'
  secret_url_cloudamqp_sneakers: 'amqp://guest:guest@localhost:5672'
# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_url_cloudamqp_bunny: <%= ENV["BUNNY_CLOUDAMQP_URL"] %>
  secret_url_cloudamqp_sneakers: <%= ENV["SNEAKERS_CLOUDAMQP_URL"] %>
